apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prime-checker-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: prime-checker
  namespaceSelector:
    matchNames:
      - prime-checker
  endpoints:
    - port: http
      path: /metrics
      interval: 15s